[package]
name = "arb_hash"
version = "0.1.5"
edition = "2021"
repository = "https://github.com/970037201/arb_hash_rs"
license = "GPL-3.0"
description = "Arbitrary block length hash function, potentially cryptographically secure. "

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["hash", "digest", "block"]
block = []
digest = ["hash", "block"]
hash = ["block"]