[package]
name = "arb_hash"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/970037201/arb_hash_rs"
license = "GPL-3.0"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
